# This rule is not used by the project remote-cluster-provisioner itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over infra.dcn.ssu.ac.kr.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: remote-cluster-provisioner
    app.kubernetes.io/managed-by: kustomize
  name: remotecluster-admin-role
rules:
- apiGroups:
  - infra.dcn.ssu.ac.kr
  resources:
  - remoteclusters
  verbs:
  - '*'
- apiGroups:
  - infra.dcn.ssu.ac.kr
  resources:
  - remoteclusters/status
  verbs:
  - get
