apiVersion: infra.dcn.ssu.ac.kr/v1
kind: RemoteCluster
metadata:
  labels:
    app.kubernetes.io/name: remote-cluster-provisioner
    app.kubernetes.io/managed-by: kustomize
  name: remotecluster-sample
spec:
  host: "192.168.3.182"
  port: 22
  user: "ubuntu"

  auth:
    passwordSecretRef:
      name: remote-cluster-credentials

  kubernetes:
    version: "v1.29.3"

---
apiVersion: v1
kind: Secret
metadata:
  name: remote-cluster-credentials
  namespace: default
type: Opaque
stringData:
  password: "1"
