apiVersion: infra.dcn.ssu.ac.kr/v1
kind: RemoteCluster
metadata:
  labels:
    app.kubernetes.io/name: remote-cluster-provisioner
    app.kubernetes.io/managed-by: kustomize
  name: remotecluster-sample
spec:
  # TODO(user): Add fields here
